[tools]
node = { version = "{{ env['NODE_VERSION'] | default(value='lts') }}" }

[tasks]
  [tasks.build]
  run = [{ task = "//projects/...:build" }]

  [tasks.lint]
  depends = [ "build" ]
  run = [
    "tsc --noEmit",
    "eslint",
    { task = "//projects/...:lint" },
  ]

  [tasks.fix]
  depends = [ "build" ]
  run = [
    "eslint --fix",
    { task = "//projects/...:fix" },
  ]

  [tasks.test]
  run = [{ task = "//projects/...:test" }]

  [tasks.clean]
  run = "git clean -dX --exclude=\"!mise.local.toml\" --force"

  [tasks.refresh]
  depends = [ "clean" ]
  run = [
    "rm --force ./pnpm-lock.yaml",
    "corepack enable",
    "corepack up",
    "mise install"
  ]

  [tasks.release]
  depends = [
    "release:readme",
    "build",
  ]
  run = "pnpm --recursive publish --provenance --access=public"

[hooks]
postinstall = [
  "corepack enable",
  "pnpm install",
]

[env]
_.path = "./node_modules/.bin"

[settings]
jobs = 8

# Required for hooks as of 2025.10
# https://mise.jdx.dev/hooks.html
experimental = true
