packages:
  - workspaces/*
  - examples/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver

overrides:
  "@types/eslint-plugin-jsx-a11y>@types/eslint": "npm:eslint@^9"
