packages:
  - projects/*
  - examples/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver
  - workerd

# Required to publish from tag on GitHub Actions
gitChecks: false
